### ISSUE TITLE
C# Library

### ISSUE THREAD

**Issue by MelbourneDeveloper** [moriyasu/ApolloWalletNano#1]
私は、いろいろなハードウェアウォレットのクライエントを開発しています。

https://github.com/MelbourneDeveloper/Trezor.Net

https://github.com/MelbourneDeveloper/Hardwarewallets.Net

https://github.com/MelbourneDeveloper/KeepKey.Net

https://github.com/MelbourneDeveloper/Ledger.Net

C#のクライエントを開発するつもりですか?

**Comment by moriyasu** [comment]
C#ではなく、JavaScript(node.js)での開発を予定しております。

**Comment by tease0** [comment]
😩
